# 端口号
server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC
    username: root
    password: 123456
# 分页插件
pagehelper:
  reasonable: true
  support-methods-arguments: true